PARSER_NAME  = ARGV[0]
ALOTTED_TIME = ARGV[1]

LABEL_ONE   = ARGV[2]
COMMAND_ONE = ARGV[3]

LABEL_TWO   = ARGV[4]
COMMAND_TWO = ARGV[5]

LABEL_TRE   = ARGV[6]
COMMAND_TRE = ARGV[7]

File.open("#{PARSER_NAME}.sh", "w") { |f|
  f.puts "./auto_parser_generic 7 'awa' #{ALOTTED_TIME} #{LABEL_ONE} '#{COMMAND_ONE}' #{LABEL_TWO} '#{COMMAND_TWO}' #{LABEL_TRE} '#{COMMAND_TRE}'"
}
